import Head from "next/head";
import { createPost } from "./actions";

export default function Home() {
  return (
    <>
      <Head>
        <title>moodlib</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-10 font-mono">
        <h1 className="text-2xl">moodlib</h1>
        <p className="text-sm">track your moods here</p>
        <form action={createPost}>
          <label htmlFor="text" className="mt-5 block">
            mood:
          </label>
          <textarea
            name="text"
            id="text"
            cols={30}
            rows={10}
            className="border border-black p-2"
          ></textarea>
          <button type="submit" className="block bg-black p-2 text-gray-100">
            submit
          </button>
        </form>
      </main>
    </>
  );
}
